import { readdirSync } from 'node:fs'
import { extname, join } from 'node:path'
import { resolveCaption, type Caption } from './captions'
import { loadCaptions } from './captionsFile'

const IMAGE_EXTENSIONS = new Set(['.png', '.jpg', '.jpeg', '.webp', '.avif', '.gif'])
/**
 * Clips live in the same folder as the photographs and behave the same way:
 * a rock in the pond, a tile on /about, an entry in captions.json. The only
 * difference is that one of them moves.
 */
const VIDEO_EXTENSIONS = new Set(['.mp4', '.webm', '.mov'])

/**
 * Width the pond actually needs.
 *
 * A photograph never opens wider than 600 CSS pixels, so 1200 covers a 2×
 * display with nothing to spare and nothing wasted. Straight from the camera
 * these are 2048px and up to 3.3MB each, which is an order of magnitude over
 * the PRD's 250KB budget — and the pond is the first thing anyone sees.
 */
const PHOTO_WIDTH = 1200
/**
 * Next 16 only accepts qualities from an allowlist, which defaults to [75];
 * anything else is a 400 from the optimiser rather than a slightly different
 * file. Changing this means adding the value to `images.qualities` in
 * next.config.ts as well.
 */
const PHOTO_QUALITY = 75

/**
 * Route a photograph through Next's image optimiser.
 *
 * It re-encodes to AVIF or WebP at the requested width and caches the result,
 * so the browser fetches a couple of hundred kilobytes instead of a couple of
 * megabytes. Same-origin, so it does not taint the canvas the way a
 * cross-origin image would.
 */
function optimised(src: string): string {
  return `/_next/image?url=${encodeURIComponent(src)}&w=${PHOTO_WIDTH}&q=${PHOTO_QUALITY}`
}

export type Photo = {
  /** Filename, which is the key into captions.json. */
  file: string
  /** A still or a clip. A clip loops silently; everything else is identical. */
  kind: 'image' | 'video'
  /**
   * The still the canvas loads, optimised.
   *
   * For a clip this is its poster frame. The ASCII stage is built from a
   * still either way, so the rock can draw itself long before a video has
   * buffered a single frame.
   */
  src: string
  /** The original file, kept for the filename and for a full-size link later. */
  original: string
  /** For a clip, the file to loop. Undefined for a still. */
  video?: string
  /** Description, place, date and exposure. Blank fields are omitted, never shown. */
  caption: Caption
}

/**
 * Where a clip's poster frame lives.
 *
 * Generated by scripts/video-to-loop.swift and committed, so the poster is
 * never produced at runtime and the rock has something to draw immediately.
 */
function posterFor(file: string): string {
  return `/photos/posters/${file.replace(/\.[^.]+$/, '.jpg')}`
}

/**
 * The photographs, read from public/photos at build time.
 *
 * Adding one is dropping a file in that folder — no code change and no
 * manifest to keep in step. Server-only: it touches the filesystem.
 */
export function listPhotos(): Photo[] {
  // Read once for the whole folder rather than per photograph.
  const captions = loadCaptions()
  try {
    return readdirSync(join(process.cwd(), 'public', 'photos'))
      .filter((file) => {
        const extension = extname(file).toLowerCase()
        return IMAGE_EXTENSIONS.has(extension) || VIDEO_EXTENSIONS.has(extension)
      })
      .sort()
      .map((file) => {
        const isVideo = VIDEO_EXTENSIONS.has(extname(file).toLowerCase())
        return {
          file,
          kind: isVideo ? ('video' as const) : ('image' as const),
          src: optimised(isVideo ? posterFor(file) : `/photos/${file}`),
          original: `/photos/${file}`,
          ...(isVideo ? { video: `/photos/${file}` } : {}),
          caption: resolveCaption(file, captions),
        }
      })
  } catch {
    return []
  }
}
